{% set name = "cpnest" %}
{% set version = "0.9.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 69b61eb80a6fd1399530e9e5644d7bf67054f4eadcd9a7bac641e98d01646c9c
  patches:
    - libm.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: true # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - scipy
    - pip
    - python
    - setuptools
  run:
    - corner
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - tqdm

test:
  imports:
    - cpnest
    - cpnest.NestedSampling
    - cpnest.cpnest
    - cpnest.model
    - cpnest.nest2pos
    - cpnest.parameter
    - cpnest.proposal
    - cpnest.sampler
    - cpnest.logger
  commands:
    # cpnest.plot imports matplotlib.pyplot but doesn't force
    # a non-interactive backend (which is fine | DMM)
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND="Agg"  # [unix]
    - python -c "import cpnest.plot"

about:
  home: "https://github.com/johnveitch/cpnest"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "CPNest: Parallel nested sampling"
  doc_url: "https://johnveitch.github.io/cpnest/"
  dev_url: "https://github.com/johnveitch/cpnest"

extra:
  recipe-maintainers:
    - duncanmmacleod
    - johnveitch
    - wdpozzo
