{% set name = "cpnest" %}
{% set version = "0.11.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_rev: v{{ version }}
  git_url: https://github.com/johnveitch/cpnest.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  skip: true  # [py<30 or python_impl != 'cpython']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - scipy
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - corner
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - tqdm

test:
  imports:
    - cpnest
    - cpnest.NestedSampling
    - cpnest.cpnest
    - cpnest.model
    - cpnest.nest2pos
    - cpnest.parameter
    - cpnest.proposal
    - cpnest.sampler
    - cpnest.utils
  commands:
    # cpnest.plot imports matplotlib.pyplot but doesn't force
    # a non-interactive backend (which is fine | DMM)
    - setx MPLBACKEND "Agg"  # [win]
    - export MPLBACKEND="Agg"  # [unix]
    - python -c "import cpnest.plot"

about:
  home: "https://github.com/johnveitch/cpnest"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "CPNest: Parallel nested sampling"
  doc_url: "https://johnveitch.github.io/cpnest/"
  dev_url: "https://github.com/johnveitch/cpnest"

extra:
  recipe-maintainers:
    - duncanmmacleod
    - johnveitch
    - wdpozzo
