{% set name = "cpnest" %}
{% set version = "0.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aecff88b08e39592cbea8928cc2ce1c69f22f695a2d7e3f32f410080873db668
  patches:
    - no-requires-cython.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [python_impl != 'cpython']

requirements:
  build:
    - {{ compiler('c') }}
    # extras for cross compiling
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
    - scipy
    - setuptools
    - setuptools_scm
  run:
    - corner
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - tqdm

test:
  requires:
    - pip
  imports:
    - cpnest
    - cpnest.parameter
  commands:
    # check requirements
    - python -m pip check

about:
  home: https://github.com/johnveitch/cpnest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "CPNest: Parallel nested sampling"
  doc_url: https://johnveitch.github.io/cpnest/
  dev_url: https://github.com/johnveitch/cpnest

extra:
  recipe-maintainers:
    - duncanmmacleod
    - johnveitch
    - wdpozzo
