{% set name = "cpnest" %}
{% set version = "0.11.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7efc83e63e9571b962530434de44b40b0e8c6d29da348cb59e650236ab0b01b8

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py < 39 or python_impl != 'cpython']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    # extras for cross compiling
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - corner
    - matplotlib-base
    - numpy
    - python
    - scipy
    - tqdm

test:
  requires:
    - pip
  imports:
    - cpnest
    - cpnest.parameter
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show cpnest

about:
  home: https://github.com/johnveitch/cpnest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'CPNest: Parallel nested sampling'
  doc_url: https://johnveitch.github.io/cpnest/
  dev_url: https://github.com/johnveitch/cpnest

extra:
  recipe-maintainers:
    - duncanmmacleod
    - johnveitch
    - wdpozzo
