travis:
  secure:
    BINSTAR_TOKEN: E1ACq+Ao+vfRR5+6M1Wn/dknKK5JVlmy0G5tiCxUqUlHhmMx19njtJjmC5FQKJsZBXyrE6PsQ0+L3O+++f++gb5O2PQ5MRqrA3KB6f8Ae/PsvjABFgnRmx5FeEygVTU1A1DuebS6KbgZL/GvQHqW2LGrYk5Ogt+mT3Yv3dGJuP69ZEfzAuDvZkwwLW7k1fEJKgLBhYRNgzapmNUkWLy0izJVoI+phAL0o47j2Nycshn0pGyUUpXUZp9uRFRtQCZqVtTsvfnCOWFF64S+M3zqY0sJR30VypetqLlOq+DvhyFaWxjx2isDpPWekrsdX+we0v31P81Q7R+qWS7yQqspUxyEMnhxfq9ATeKbDAwF7W15nQholvX4QWb5HpL3ctb8RtebcE0nHG4PiW8VGcim7sw9YdC8xTMsLzJVcwxEZufPGC+ZNXTMG9HuCc78f/gznR6WExh5q6wX8SLCTr5rGOVSvEIE0l9Xqu0hZ2e/W30awiu8ED8x52oMiPe3xZviKW4GtsJ5VgJYU+Cjl/ZB/bf2gPLUUIL7Kqc47CfbL+DOqqD8Zh5Z/lYlqnVsNbemljnKEB4Xyptz0OGBh389aq+GOqOV/Dj0XZowKPRQRUGpGohAUn/4fmL0SGidCNUOd6ho1d1kTIa2tK43yHbTgkfsR7OLV/xdq27CUjrvgEs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
